last.holidays:
  location: Bavaria
  year: 2023
  verdict: great

countries:
    visited: Argentina, Brazil, Italy, Spain


app:
  menus:
    - title: Home
      name: Home
      path: /
    - title: Login
      name: Login
      path: /login
  compiler:
    timeout: 5
    output-folder: /temp/
  error: /error/
